### ISSUE TITLE
Config registry should be applicable to the explorer configs

### ISSUE THREAD

**Issue by ggoranov** [dusk-network/dusk-explorer#10]
- `dusk-exporer.toml` should be the name of config file instead of the default one `dusk.toml`
- Config registry should include explorer config section

```toml
# general node configs
[general]
network = "testnet"

[explorer]
port=4000

```

- `config.defineENV` and `config.defineFlags` should be redefined by each node.

E.g currently on `dusk-explorer --help`,  a misleading help message is printed
```      
Usage of Dusk node:
...
  -w, --wallet.file string       sets the wallet file to use (default "wallet.dat")
  -d, --wallet.store string      sets the wallet database directory (default "walletDB")
...
```
